apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
spec:
  selector:
    matchLabels:
      app: mongodb-express
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
      - name: mongodb-express
        image: mongo-express
        ports: 
          - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: # secret(in kubernetes) will fill this
            secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: # secret(in kubernetes) will fill this
            secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: # secret(in kubernetes) will fill this
            configMapKeyRef:
                name: mongodb-configmap
                key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongodb-express
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000 # port for external ip address access